### ISSUE TITLE
Tree editing/construction GUI

### ISSUE THREAD

**Issue by heuristicus** [splintered-reality/rqt_py_trees#5]
This would be useful to have for users who don't need or want to look at the code directly. Also useful for educational purposes to allow people to play around with the tree and see what effects changing things has without having to touch code.

This would be a python parser and a template generator which generates code for trees based on some internal structure. Use the parser to read behaviour definitions in user specified directories and make the behaviours available with names, variables and so on, all of which can be modified in the editor. Would also need to consider decorators. Once the tree is finished, have an export button which generates a python file containing the code to generate the whole tree. An option to specify subtrees would probably be nice, so that separate classes can be generated for distinct parts of the tree, or those which might be repeated.

The trees would be modifiable using the mouse. Dragging a behaviour moves it and all of its children around, and releasing the mouse drops it in as a child of the closest behaviour on the level above. Will need to use the positions of all other behaviours to determine the changed status. Selecting a behaviour gives access to a pop-up window or a sidebar which displays all of the initialisation variables of the behaviour, and allows them to be specified. Should also be able to apply decorators to the behaviour from this window.
## Minimal functionality
- [ ] behaviour/decorator parsing
- [ ] display of available behaviours
- [ ] modification of behaviour variables
- [ ] python code generation from created trees
- [ ] ability to move behaviours around in the gui (not necessarily via mouse). An initial implementation could be something like selecting which behaviour to move via a right click menu, and where to move it to via another one on the node you want to move to.

**Comment by stonier** [comment]
Aging out. New development is in a js framework - [py_trees_js](https://github.com/splintered-reality/py_trees_js).

No plan as yet for an editor.
